import { StyleSheet } from "react-native";
import { normalizeFont, scale, vScale } from "./responsive";

const challangeStyles = (screenWidth: number, screenHeight: number) =>
  StyleSheet.create({
    leageImage: {},
    container: {
      flex: 1,
      justifyContent: "flex-start",
      backgroundColor: "#edededff",
    },
    itemsContainer: {
      width: screenWidth * 1,
      height: "auto",
      justifyContent: "center",
      alignItems: "center",
      gap: 15,
    },
    inputItem: {
      fontSize: 16,
      backgroundColor: "#fff",
      borderRadius: 5,
      width: "100%",
      minHeight: 40,
      maxHeight: 100,
      paddingLeft: 15,
    },
    inputContainer: {
      width: "90%",
      backgroundColor: "rgba(76, 0, 130, 0.07)",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: 5,
      borderRadius: 5,
    },
    addPoolsInput: {
      fontSize: 16,
      backgroundColor: "#fff",
      borderRadius: 5,
      width: "80%",
      minHeight: 40,
      maxHeight: 80,
      paddingLeft: 15,
    },
    indexItems: {
      width: "90%",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 5,
      backgroundColor: "#f9f9f9",
    },
    text: {
      width: "80%",
      fontFamily: "sarif",
      fontSize: 16,
      fontWeight: "bold",
    },
    predictText: {
      fontSize: 17,
      color: "#008000",
      width: "90%",
      fontWeight: "bold",
    },
    time: {
      width: "40%",
      padding: 10,
      borderRadius: 5,
      backgroundColor: "rgba(76, 0, 130, 0.07)",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-evenly",
    },
    create: {
      width: "20%",
      height: 65,
      borderRadius: 100,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(76, 0, 130, 0.07)",
    },
    createChallenge: {
      width: "90%",
      height: 45,
      borderRadius: 5,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#4B0082",
    },
    createText: {
      fontSize: 17,
      color: "#fff",
      textAlign: "center",
      fontWeight: "bold",
    },
    header: {
      width: "97%",
      height: vScale(90, screenHeight),
      top: vScale(2, screenHeight),
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#ffffff",
      borderRadius: Math.round(scale(5, screenWidth)),
      shadowColor: "#000",
      shadowOpacity: 0.05,
      elevation: 3,
      justifyContent: "space-between",
      paddingHorizontal: scale(10, screenWidth),
    },
    userHeader: {
      width: "97%",
      height: scale(90, screenWidth),
      top: vScale(2, screenHeight),
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#ffffff",
      borderRadius: Math.round(scale(5, screenWidth)),
      shadowColor: "#000",
      shadowOpacity: 0.05,
      elevation: 3,
      justifyContent: "space-between",
      marginLeft: scale(5, screenWidth),
      paddingHorizontal: scale(10, screenWidth),
    },
    challengeList: {
      width: "100%",
      height: scale(700, screenWidth),
      overflow: "hidden",
      justifyContent: "flex-start",
    },
    userInfo: {
      width: scale(50, screenWidth),
      height: scale(50, screenWidth),
      flexDirection: "row",
      overflow: "hidden",
      alignItems: "center",
      borderRadius: Math.round(scale(100, screenWidth)),
      borderWidth: 1,
      backgroundColor: "#transparent",
      borderColor: "#cccccc",
      marginRight: scale(10, screenWidth),
      shadowOpacity: 0.05,
      elevation: 3.5,
    },
    profilePicture: {
      width: scale(50, screenWidth),
      height: scale(50, screenWidth),
    },
    username: {
      fontSize: normalizeFont(18, screenWidth, screenHeight),
      fontWeight: "bold",
      fontFamily: "serif",
    },
    userInfos: {
      flexDirection: "column",
    },
    authorUsername: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      fontFamily: "serif",
      fontWeight: "bold",
      marginLeft: scale(10, screenWidth),
    },
    arrowback: {
      marginLeft: scale(10, screenWidth),
    },
    voterUsername: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      fontWeight: "bold",
      fontFamily: "serif",
    },
    challengeItemsContainer: {
      width: "100%",
      height: "auto",
      backgroundColor: "#fff",
      borderRadius: Math.round(scale(5, screenWidth)),
    },
    usersMainContainer: {
      width: "100%",
      height: "100%",
      gap: 10,
      padding: 7,
    },
    backText: {
      fontSize: 18,
      fontWeight: "bold",
      top: 12,
      color: "#4B0082",
    },
    userPredictText: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      color: "#000",
      width: "90%",
      fontWeight: "semibold",
    },
    adminText: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      color: "#4B0082",
      fontWeight: "bold",
    },
    challengeItem: {
      width: "100%",
      height: "auto",
      padding: scale(10, screenWidth),
      top: vScale(20, screenHeight),
      flexDirection: "row",
      justifyContent: "space-around",
    },
    challengeItemQuestion: {
      width: "100%",
      padding: scale(10, screenWidth),
      bottom: vScale(10, screenHeight),
      flexDirection: "row",
      justifyContent: "space-around",
    },
    challengeVotes: {
      width: "100%",
      padding: 10,
      top: 70,
    },
    currentTime: {
      width: "40%",
      padding: 10,
      borderBottomWidth: 1,
      borderBottomColor: "#eee",
      justifyContent: "space-between",
      alignItems: "center",
    },
    currentTimeText: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      color: "#4B0082",
      fontWeight: "500",
    },
    itemTime: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      fontWeight: "bold",
    },
    currentDate: {
      width: "40%",
      padding: 10,
      height: 50,
      bottom: 15,
      borderBottomWidth: 1,
      borderBottomColor: "#eee",
      flexDirection: "row",
      alignItems: "center",
    },
    poolContainer: {
      backgroundColor: "rgba(76, 0, 130, 0.07)",
      padding: scale(10, screenWidth),
      marginVertical: scale(5, screenWidth),
      borderRadius: Math.round(scale(10, screenWidth)),
      alignItems: "baseline",
    },
    poolBlurContainer: {
      padding: scale(10, screenWidth),
      marginVertical: scale(5, screenWidth),
      borderRadius: Math.round(scale(10, screenWidth)),
      width: "100%",
      alignItems: "baseline",
    },
    pools: {
      width: "100%",
      padding: scale(10, screenWidth),
    },
    poolText: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      color: "#000",
      fontWeight: "500",
    },
    answerInput: {
      width: "90%",
      padding: scale(10, screenWidth),
      bottom: vScale(10, screenHeight),
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      borderWidth: 1,
      borderColor: "#00000031",
      borderRadius: Math.round(scale(5, screenWidth)),
      minHeight: vScale(50, screenHeight),
      maxHeight: "auto",
    },
    challengeItems: {
      width: "100%",
      padding: 10,
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "space-between",
    },
    challengeDetailsContainer: {
      width: "100%",
      height: scale(80, screenHeight),
      overflow: "hidden",
      alignItems: "flex-end",
      borderWidth: 2,
      borderColor: "#eee",
      borderRadius: Math.round(scale(5, screenWidth)),
    },
    challengeTextContainer: {
      marginLeft: scale(10, screenWidth),
      marginTop: vScale(5, screenHeight),
    },
    challengeDetails: {
      gap: scale(13, screenWidth),
      height: "auto",
      width: "100%",
      backgroundColor: "#fff",
      borderRadius: Math.round(scale(5, screenWidth)),
      overflow: "hidden",
    },
    challengeFee: {
      position: "absolute",
      width: "auto",
      right: scale(0, screenWidth),
      height: vScale(27, screenHeight),
      backgroundColor: "rgb(255, 230, 0)",
      borderBottomLeftRadius: Math.round(scale(15, screenWidth)),
      paddingVertical: vScale(5, screenHeight),
      paddingHorizontal: scale(10, screenWidth),
    },
    freeEntryText: {
      fontSize: normalizeFont(12, screenWidth, screenHeight),
      fontWeight: "bold",
    },
    challengeitems: {
      width: "80%",
      marginTop: scale(10, screenWidth),
      marginLeft: scale(30, screenWidth),
      borderTopWidth: 1,
      borderTopColor: "#ccc",
      borderBottomWidth: 1,
      borderBottomColor: "#cccc",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    backgrounImage: {
      width: screenWidth * 1,
      height: screenHeight * 0.33,
      objectFit: "cover",
      borderRadius: 5,
    },
    creator: {
      marginLeft: scale(3, screenWidth),
      marginTop: vScale(10, screenHeight),
      height: scale(50, screenWidth),
      flexDirection: "row",
      overflow: "hidden",
    },
    leageImage: {
      width: scale(50, screenWidth),
      height: scale(50, screenWidth),
      overflow: "hidden",
      borderRadius: Math.round(scale(100, screenWidth)),
      borderWidth: 1,
      borderColor: "#ccc",
      shadowOpacity: 0.05,
      elevation: 1,
    },
    startDate: {
      width: "40%",
      marginTop: vScale(10, screenHeight),
      flexDirection: "row",
      alignItems: "center",
    },
    endDate: {
      width: "40%",
      padding: scale(10, screenWidth),
      marginTop: vScale(10, screenHeight),
      flexDirection: "row",
      alignItems: "center",
    },
    startDateText: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      color: "#000000b0",
      marginLeft: scale(5, screenWidth),
      marginTop: vScale(5, screenHeight),
    },
    detailText: {
      fontSize: normalizeFont(14.5, screenWidth, screenHeight),
      fontFamily: "poppins",
      color: "#000000b0",
      marginBottom: vScale(10, screenHeight),
    },
    challengeStatus: {
      width: "27%",
      height: vScale(27, screenHeight),
      marginLeft: scale(10, screenWidth),
      borderRadius: Math.round(scale(15, screenWidth)),
      backgroundColor: "rgba(76, 0, 130, 0.1)",
      alignItems: "center",
    },
    challengeItemsStatus: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
      marginRight: scale(10, screenWidth),
    },
    challengeitem: {
      width: "100%",
      flexDirection: "row",
    },
    challengeTime: {
      fontSize: normalizeFont(13, screenWidth, screenHeight),
      color: "#0000009f",
      fontWeight: "bold",
      marginTop: scale(5, screenWidth),
      marginLeft: scale(10, screenWidth),
    },
    backButton: {
      flexDirection: "row",
      alignItems: "center",
      bottom: vScale(15, screenHeight),
    },
    dontMissOutText: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      fontWeight: "bold",
      color: "#4B0082",
    },
    checkItOutButton: {
      borderRadius: Math.round(scale(5, screenWidth)),
      borderWidth: 1,
      borderColor: "#0000005e",
      justifyContent: "center",
      alignItems: "center",
      width: "45%",
      marginLeft: "53%",
      bottom: vScale(11, screenHeight),
      height: vScale(37, screenHeight),
    },
    checkItOutText: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      fontWeight: "bold",
      color: "#ffffff",
    },
    activeChallenge: {
      backgroundColor: "rgba(6, 151, 6, 0.16)",
      flexDirection: "row",
      justifyContent: "space-evenly",
      alignItems: "center",
      left: scale(0.66, screenWidth),
      width: "25%",
      color: "green",
      bottom: scale(0, screenHeight),
    },
    textActive: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      fontWeight: "bold",
    },
    textActiveChallenge: {
      color: "green",
      fontSize: normalizeFont(12, screenWidth, screenHeight),
      fontWeight: "bold",
    },
    textEndedChallenge: {
      color: "red",
      fontSize: normalizeFont(12, screenWidth, screenHeight),
      fontWeight: "bold",
    },
    textUpcomingChallenge: {
      color: "#4B0082",
      fontSize: normalizeFont(12, screenWidth, screenHeight),
      fontWeight: "bold",
    },
    voteCount: {
      position: "absolute",
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      color: "#4B0082",
      fontWeight: "bold",
      bottom: vScale(10, screenHeight),
    },
    icon: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      left: 290,
      top: 38,
      position: "absolute",
      borderRadius: 10,
    },
    endedChallenge: {
      backgroundColor: "rgba(133, 4, 4, 0.3)",
      flexDirection: "row",
      justifyContent: "space-evenly",
      alignItems: "center",
    },
    upcomingChallenge: {
      backgroundColor: "rgba(76, 0, 130, 0.26)",
      flexDirection: "row",
      justifyContent: "space-evenly",
      alignItems: "center",
    },
    voteButtonContainer: {
      width: "70%",
      height: vScale(50, screenHeight),
      left: scale(55, screenWidth),
      marginTop: vScale(30, screenHeight),
      justifyContent: "center",
      alignItems: "center",
      borderRadius: Math.round(scale(5, screenWidth)),
      backgroundColor: "#4B0082",
    },
    voteButtonText: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      color: "#ffffff",
      fontWeight: "bold",
    },
    voteButton: {
      width: "100%",
      height: "80%",
      borderRadius: 5,
      backgroundColor: "#4B0082",
      justifyContent: "center",
      alignItems: "center",
    },
    answerPerUser: {
      width: "89%",
      height: vScale(60, screenHeight),
      padding: scale(10, screenWidth),
      borderRadius: Math.round(scale(5, screenWidth)),
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      bottom: vScale(10, screenHeight),
      left: scale(20, screenWidth),
      backgroundColor: "rgb(250, 128, 128)",
    },
    answerPerUserText: {
      fontSize: normalizeFont(13, screenWidth, screenHeight),
      width: "90%",
      color: "#ffffff",
      fontWeight: "bold",
    },
    voteContainer: {
      width: "100%",
      height: "auto",
      padding: scale(10, screenWidth),
    },
    votes: {
      width: "100%",
      minHeight: "auto",
      maxHeight: 100,
      paddingTop: 10,
      bottom: 20,
      borderBottomWidth: 1,
      borderBottomColor: "#eee",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    userItems: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",

      borderRadius: Math.round(scale(5, screenWidth)),
      marginBottom: vScale(10, screenHeight),
      width: "100%",
    },
    user: {
      flexDirection: "row",
      alignItems: "center",
      overflow: "hidden",
    },
    userItem: {
      width: scale(50, screenWidth),
      height: scale(50, screenWidth),
      borderRadius: Math.round(scale(100, screenWidth)),
      marginRight: scale(10, screenWidth),
      borderColor: "#cccccc",
      overflow: "hidden",
      borderWidth: 1,
      shadowOpacity: 0.05,
      elevation: 2.5,
    },
    itemProfilePicture: {
      width: "100%",
      height: "100%",
    },
    createdAT: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      color: "#555",
    },
    voteTextContainer: {
      width: "99%",
      backgroundColor: "#f0f0f0",
      height: "auto",
      left: scale(10, screenWidth),

      borderRadius: Math.round(scale(5, screenWidth)),
    },
    voteText: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      color: "#000",
      padding: 10,
    },
    modalContainer: {
      flex: 1,
      marginTop: vScale(0, screenHeight),
      height: "100%",
      width: "100%",
      position: "absolute",
      backgroundColor: "#fff",
    },
    titleContainer: {
      height: vScale(8, screenHeight),
      paddingLeft: scale(10, screenWidth),
      marginTop: vScale(5, screenHeight),
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    titleContainers: {
      flexDirection: "row",
      alignItems: "center",
      position: "absolute",
      gap: scale(20, screenWidth),
      marginLeft: scale(20, screenWidth),
      marginTop: vScale(120, screenHeight),
    },
    press: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      width: scale(45, screenWidth),
      height: vScale(45, screenHeight),
      borderWidth: 1,
      borderColor: "#00000029",
      borderRadius: Math.round(scale(8, screenWidth)),
    },
    titleText: {
      fontSize: normalizeFont(20, screenWidth, screenHeight),
      fontWeight: "bold",
    },
    childrenContainer: {
      flex: 1,
      alignItems: "center",
      gap: scale(40, screenWidth),
      marginTop: vScale(20, screenHeight),
    },
    sectionHeader: {
      fontSize: normalizeFont(17, screenWidth, screenHeight),
      fontWeight: "bold",
      color: "#4B0082",
      marginLeft: vScale(15, screenHeight),
      paddingVertical: vScale(10, screenHeight),
      paddingHorizontal: scale(10, screenWidth),
    },
    sectionHeaderStyle: {
      width: "100%",
      height: "auto",
      backgroundColor: "#ffffff",
    },
    sectionHeaderStyles: {
      width: "100%",
    },
    sectionHeaderContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    sectionHeaderMore: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      fontWeight: "600",
      color: "#000",
      marginRight: scale(15, screenWidth),
    },
    seprationLine: {
      width: "100%",
      height: scale(0.5, screenHeight),
      backgroundColor: "#ccccccc5",
      marginBottom: vScale(0, screenHeight),
    },
    containers: {
      width: "100%",
      height: "auto",
      overflow: "hidden",
      justifyContent: "flex-start",
      backgroundColor: "#e8e8e8",
    },
    userPredictContainer: {
      width: "98%",
      height: "auto",
      backgroundColor: "#fff",
      borderRadius: Math.round(scale(5, screenWidth)),
      justifyContent: "flex-start",
      alignItems: "center",
      overflow: "hidden",
      marginLeft: scale(2, screenWidth),
    },
    userPredictInstrutions: {
      fontSize: normalizeFont(17, screenWidth, screenHeight),
      color: "#4B0082",
      right: scale(60, screenWidth),
      bottom: scale(25, screenWidth),
      fontWeight: "bold",
    },
    liveContainer: {
      flexDirection: "row",
      alignItems: "center",
      position: "absolute",
      right: scale(-20, screenWidth),
      width: scale(90, screenWidth),
      height: vScale(40, screenHeight),
      borderRadius: Math.round(scale(30, screenWidth)),
      backgroundColor: "rgba(6, 128, 32, 0.1)",
      justifyContent: "center",
    },
    live: {
      fontSize: normalizeFont(12, screenWidth, screenHeight),
      color: "#4B0082",
      fontWeight: "bold",
      marginRight: scale(18, screenWidth),
    },
    instruction: {
      width: "100%",
      height: scale(40, screenWidth),
      overflow: "hidden",
      alignItems: "center",
      justifyContent: "flex-start",
      flexDirection: "row",
      marginTop: vScale(10, screenHeight),
    },
    trophyContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginTop: vScale(5, screenHeight),
    },
    trophyIcon: {
      marginLeft: scale(10, screenWidth),
      backgroundColor: "#d6b6042a",
      width: scale(35, screenWidth),
      height: scale(35, screenWidth),
      borderRadius: Math.round(scale(15, screenWidth)),
      justifyContent: "center",
      bottom: vScale(2, screenHeight),
      alignItems: "center",
    },
    peopleIcon: {
      marginLeft: scale(10, screenWidth),
      backgroundColor: "#4b00821a",
      width: scale(35, screenWidth),
      height: scale(35, screenWidth),
      borderRadius: Math.round(scale(15, screenWidth)),
      justifyContent: "center",
      bottom: vScale(2, screenHeight),
      alignItems: "center",
    },
    trophyText: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      color: "#000",
      marginLeft: scale(5, screenWidth),
      fontWeight: "500",
      bottom: vScale(2, screenHeight),
    },
    seprationLineVertical: {
      width: scale(1, screenWidth),
      height: vScale(40, screenHeight),
      backgroundColor: "#ccccccc5",
      marginHorizontal: scale(15, screenWidth),
    },
    joinChallange: {
      width: "90%",
      height: vScale(40, screenHeight),
      backgroundColor: "#4B0082",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: Math.round(scale(5, screenWidth)),
      marginTop: vScale(30, screenHeight),
      marginBottom: vScale(8, screenHeight),
    },
    joinChallangeText: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      color: "#ffffff",
      fontWeight: "bold",
    },
    aboutChallengeText: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      color: "#4b0082",
      fontWeight: "500",
      marginRight: scale(190, screenWidth),
      marginTop: vScale(10, screenHeight),
      marginBottom: vScale(10, screenHeight),
    },
    challengeTitle: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      color: "#000",
      paddingLeft: vScale(25, screenHeight),
    },
    rulesAndRequirements: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      color: "#000",
      fontWeight: "500",
      marginTop: vScale(10, screenHeight),
      marginLeft: scale(10, screenWidth),
    },
    space: {
      height: vScale(15, screenHeight),
    },
    expandButton: {
      width: "100%",
      height: vScale(40, screenHeight),
      overflow: "hidden",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: scale(10, screenWidth),
      flexDirection: "row",
    },
    expandButtonContent: {
      width: "70%",
      flexDirection: "row",
      alignItems: "center",
      gap: scale(4, screenWidth),
    },
    expandButtonText: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
    },
    gppIcon: {
      backgroundColor: "#00000028",
      width: scale(29, screenWidth),
      height: scale(29, screenWidth),
      borderRadius: Math.round(scale(15, screenWidth)),
      justifyContent: "center",
      alignItems: "center",
    },
    participateContainer: {
      marginTop: scale(8, screenWidth),
      marginLeft: scale(30, screenWidth),
    },
    participate: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      color: "#000",
      fontWeight: "500",
      gap: vScale(5, screenHeight),
      paddingVertical: vScale(3, screenHeight),
      paddingHorizontal: scale(5, screenWidth),
      marginBottom: vScale(5, screenHeight),
    },
    whatNextText: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      color: "#000",
      fontWeight: "500",
      padding: scale(5, screenWidth),
    },
    prizePoolContainer: {
      width: "100%",
      height: "auto",
      padding: scale(10, screenWidth),
      justifyContent: "center",
      alignItems: "center",
    },
    prizeAmountMainContainer: {
      flexDirection: "row",
      alignItems: "center",
      width: "90%",
      height: scale(40, screenWidth),
      overflow: "hidden",
      backgroundColor: "#07807094",
      borderRadius: Math.round(scale(5, screenWidth)),
    },
    capion: {
      width: "20%",
      height: scale(40, screenWidth),
      backgroundColor: "#68f73c42",
      paddingHorizontal: scale(10, screenWidth),
      position: "absolute",
      justifyContent: "center",
      alignItems: "center",
      right: scale(80, screenWidth),
      borderStartEndRadius: Math.round(scale(100, screenWidth)),
      borderStartStartRadius: Math.round(scale(100, screenWidth)),
      borderEndEndRadius: Math.round(scale(100, screenWidth)),
      borderEndStartRadius: Math.round(scale(100, screenWidth)),
    },
    prizeAmountContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      width: "60%",
      height: scale(40, screenWidth),
      backgroundColor: "#0a17d441",
      paddingHorizontal: scale(10, screenWidth),
      borderEndStartRadius: Math.round(scale(100, screenWidth)),
      borderEndEndRadius: Math.round(scale(100, screenWidth)),
      overflow: "hidden",
    },
    prizeAmountText: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      color: "#fff",
      fontWeight: "500",
    },
    createChallengeContainer: {
      width: "100%",
      height: "auto",
      padding: scale(10, screenWidth),
      backgroundColor: "#fff",
    },
    addLeagueImageText: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      fontWeight: "500",
      marginLeft: scale(220, screenWidth),
    },
    leagueImagePicker: {
      width: "25%",
      height: scale(85, screenWidth),
      borderRadius: Math.round(scale(100, screenWidth)),
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#f0f0f0",
      position: "absolute",
      right: scale(20, screenWidth),
      marginTop: vScale(40, screenHeight),
    },
    leagueImage: {
      width: "100%",
      backgroundColor: "#f0f0f0",
      height: "100%",
      borderRadius: Math.round(scale(100, screenWidth)),
      objectFit: "cover",
      shadowColor: "#000",
      shadowOpacity: 0.1,
      elevation: 5,
    },
    textInput: {
      width: scale(230, screenWidth),
      height: vScale(50, screenHeight),
      borderWidth: 1,
      borderColor: "#cccccc",
      paddingHorizontal: scale(10, screenWidth),
      borderRadius: Math.round(scale(5, screenWidth)),
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      marginTop: vScale(20, screenHeight),
      marginHorizontal: scale(10, screenWidth),
    },
    textInputs: {
      width: "95%",
      height: vScale(50, screenHeight),
      borderWidth: 1,
      borderColor: "#cccccc",
      paddingHorizontal: scale(10, screenWidth),
      borderRadius: Math.round(scale(5, screenWidth)),
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      marginTop: vScale(20, screenHeight),
      marginHorizontal: scale(10, screenWidth),
    },
    optionContainer: {
      width: "100%",
      padding: scale(7, screenWidth),
      marginTop: vScale(12, screenHeight),
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    textOption: {
      width: "20%",
      borderWidth: 1,
      borderColor: "#cccccc",
      paddingLeft: scale(10, screenWidth),
      borderRadius: Math.round(scale(5, screenWidth)),
      fontSize: normalizeFont(14, screenWidth, screenHeight),
    },
    textValue: {
      width: "75%",
      borderWidth: 1,
      borderColor: "#cccccc",
      paddingLeft: scale(10, screenWidth),
      borderRadius: Math.round(scale(5, screenWidth)),
      fontSize: normalizeFont(14, screenWidth, screenHeight),
    },
    buttonsContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: scale(10, screenWidth),
      justifyContent: "flex-end",
      right: scale(7, screenWidth),
    },
    addButton: {
      marginTop: vScale(12, screenHeight),
      paddingVertical: vScale(10, screenHeight),
      paddingHorizontal: scale(14, screenWidth),
      borderRadius: Math.round(scale(6, screenWidth)),
      backgroundColor: "#4B0082",
      alignItems: "center",
      justifyContent: "center",
      alignSelf: "flex-start",
    },
    addButtonText: {
      color: "#fff",
      fontSize: normalizeFont(12, screenWidth, screenHeight),
      fontWeight: "700",
    },
    optionText: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      color: "#333",
      marginTop: vScale(8, screenHeight),
      marginLeft: scale(6, screenWidth),
    },
    optionsContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginTop: vScale(8, screenHeight),
      alignItems: "flex-start",
    },
    optionItem: {
      backgroundColor: "#f6f0ff",
      borderRadius: Math.round(scale(8, screenWidth)),
      paddingVertical: vScale(6, screenHeight),
      paddingHorizontal: scale(10, screenWidth),
      marginRight: scale(8, screenWidth),
      marginTop: vScale(6, screenHeight),
      borderWidth: 1,
      borderColor: "#efe6ff",
    },
    questionContainer: {
      flex: 1,
      backgroundColor: "#fff",
      width: "100%",
      padding: scale(10, screenWidth),
    },
    questionText: {
      fontSize: normalizeFont(15, screenWidth, screenHeight),
      color: "#222",
      fontWeight: "700",
      marginBottom: vScale(8, screenHeight),
    },
    dateTimeContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    inputContainerDate: {
      width: "32%",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: scale(5, screenWidth),
      marginTop: vScale(16, screenHeight),
      paddingHorizontal: scale(10, screenWidth),
      paddingVertical: vScale(8, screenHeight),
    },
    dateText: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      color: "#555",
    },
    createChallengeButton: {
      width: "90%",
      height: vScale(50, screenHeight),
      backgroundColor: "#4B0082",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: Math.round(scale(5, screenWidth)),
      marginLeft: scale(20, screenWidth),
      marginBottom: vScale(60, screenHeight),
    },
    createChallengeText: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      color: "#ffffff",
      fontWeight: "bold",
    },
    scrollView: {
      flex: 1,
    },
    statusMessageContainer: {
      width: "100%",
      height: "auto",
      overflow: "hidden",
      flexDirection: "row",
      justifyContent: "center",
      backgroundColor: "#fff",
      alignItems: "center",
      paddingVertical: vScale(10, screenHeight),
      gap: scale(10, screenWidth),
    },
    statusMessageBox: {
      width: "78%",
      height: vScale(60, screenHeight),
      justifyContent: "center",
      alignItems: "center",
      borderRadius: Math.round(scale(5, screenWidth)),
      borderLeftWidth: scale(7, screenWidth),
      borderLeftColor: "#4B0082",
      backgroundColor: "#f0f0f0",
      paddingHorizontal: scale(10, screenWidth),
    },
    statusMessageText: {
      fontSize: normalizeFont(13, screenWidth, screenHeight),
      fontWeight: "500",
    },
    loadingContainer: {
      paddingHorizontal: scale(16, screenWidth),
      alignItems: "center",
      paddingVertical: vScale(40, screenHeight),
    },
    loadingText: {
      marginTop: vScale(10, screenHeight),
      color: "#999",
      textAlign: "center",
    },
    questionMainContainer: {
      width: "100%",
      height: "auto",
      backgroundColor: "#fff",
      paddingVertical: vScale(10, screenHeight),
      marginTop: vScale(10, screenHeight),
    },
    questiontext: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      color: "#4b0082",
      fontWeight: "500",
      marginLeft: scale(15, screenWidth),
    },
    optionContainers: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginTop: vScale(10, screenHeight),
      paddingHorizontal: scale(10, screenWidth),
      gap: scale(10, screenWidth),
    },
    isVoting: {
      flexDirection: "row",
      alignItems: "center",
      marginLeft: scale(15, screenWidth),
      paddingVertical: scale(10, screenWidth),
      paddingHorizontal: scale(12, screenWidth),
      borderRadius: Math.round(scale(8, screenWidth)),
      borderWidth: 1,
      borderColor: "#00000031",
    },
    questionsText: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
    },
    isSubmitting: {
      width: "90%",
      height: vScale(45, screenHeight),
      marginLeft: scale(20, screenWidth),
      top: vScale(20, screenHeight),
      borderRadius: Math.round(scale(5, screenWidth)),
      alignItems: "center",
      justifyContent: "center",
    },
  });

export default challangeStyles;
