import { StyleSheet } from "react-native";
import { normalizeFont, scale, vScale } from "./responsive";

/**
 * Create styles using current screen dimensions.
 * Usage in component:
 *   const { width, height } = useWindowDimensions();
 *   const styles = indexScreenStyles(width, height);
 */
const indexScreenStyles = (screenWidth: number, screenHeight: number) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: "#fff",
      justifyContent: "center",
      alignItems: "center",
    },
    main: {
      width: "100%",
      flex: 1,
      justifyContent: "center",
    },
    safeAreaContainer: {
      width: scale(screenWidth, screenWidth),
      marginLeft: scale(8, screenWidth),
      justifyContent: "center",
      alignItems: "center",
    },
    containerItem: {
      marginTop: vScale(0, screenHeight),
      paddingTop: vScale(0, screenHeight),
      alignItems: "flex-start",
    },
    itemCard: {
      height: vScale(screenHeight / 3.2, screenHeight),
      overflow: "hidden",
      alignItems: "center",
      justifyContent: "center",
      gap: vScale(5, screenHeight),
    },
    profileItems: {
      width: "100%",
      height: vScale(screenHeight / 9, screenHeight),
      paddingHorizontal: vScale(screenHeight / 40, screenHeight),
      paddingTop: vScale(screenHeight / 150, screenHeight),
    },
    container: {
      width: "100%",
      alignItems: "center",
      marginLeft: scale(2.5, screenWidth),
      marginTop: vScale(screenHeight / 100 - 25, screenHeight),
    },
    header: {
      width: "99%",
      borderRadius: Math.round(scale(5, screenWidth)),
      height: vScale(screenHeight / 9, screenHeight),
      flexDirection: "row",
      alignItems: "center",
    },
    profileImage: {
      width: scale(screenWidth / 6.5, screenWidth),
      height: vScale(screenHeight / 13.5, screenHeight),
      borderRadius: Math.round(scale(100, screenWidth)),
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
      borderWidth: 1,
      borderColor: "#cccccc",
      objectFit: "contain",
      shadowColor: "#000",
      shadowOpacity: 0.05,
      elevation: 3.5,
    },
    posterPfrofile: {
      width: scale(screenWidth / 7.5, screenWidth),
      height: vScale(screenHeight / 15, screenHeight),
      borderRadius: Math.round(scale(100, screenWidth)),
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
      borderWidth: 1,
      borderColor: "#cccccc",
      objectFit: "contain",
      shadowColor: "#000",
      shadowOpacity: 0.05,
      elevation: 3.5,
      marginLeft: scale(10, screenWidth),
    },
    profileImages: {
      width: "100%",
      height: "100%",
    },
    username: {
      fontSize: normalizeFont(18, screenWidth, screenHeight),
      color: "#000000",
      left: scale(screenWidth / 30, screenWidth),
      fontWeight: "bold",
      fontFamily: "serif",
    },
    createdAt: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      left: scale(12, screenWidth),
      color: "#888",
    },
    textcomment: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      marginBottom: vScale(screenHeight / 200, screenHeight),
    },
    imageContainer: {
      width: scale(screenWidth - 26, screenWidth),
      overflow: "hidden",
      height: vScale(screenHeight / 2.6, screenHeight),
      borderRadius: Math.round(scale(6, screenWidth)),
      shadowOpacity: 0.05,
      elevation: 1.5,
      marginTop: vScale((screenHeight / 90) * 0.3, screenHeight),
      right: scale(screenWidth / 100, screenWidth),
      marginBottom: vScale((screenHeight / 100) * 0.7, screenHeight),
    },
    postImage: {
      width: "100%",
      height: "100%",
    },
    optionButton: {
      marginRight: scale(15, screenWidth),
    },
    profileButton: {
      marginRight: scale(screenWidth / 1.3, screenWidth),
    },
    searchcontaiiner: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      width: "80%",
      height: vScale(screenHeight / 15, screenHeight),
      gap: vScale(3, screenHeight),
      right: scale(screenWidth / 25, screenWidth),
      position: "absolute",
      marginTop: vScale(screenHeight / 120, screenHeight),
    },
    searchContainer: {
      width: "15%",
      height: "100%",
      marginLeft: scale(screenWidth / 10, screenWidth),
      position: "absolute",
      right: scale(screenWidth / 7.5, screenWidth),
      marginTop: vScale(screenHeight / 30, screenHeight),
    },
    textsearchInput: {
      width: "70%",
      height: "100%",
      backgroundColor: "transparent",
      marginLeft: scale(screenWidth / 12, screenWidth),
      borderWidth: 1,
      borderColor: "rgba(163, 162, 162, 0.56)",
      borderRadius: Math.round(scale(30, screenWidth)),
      paddingLeft: scale(15, screenWidth),
    },
    card: {
      width: "100%",
      height: vScale(screenHeight / 3.35, screenHeight),
      borderRadius: Math.round(scale(10, screenWidth)),
      alignItems: "center",
    },
    // postcard: {
    //   width: "90%",
    //   height: screenHeight / 2.15,
    //   backgroundColor: "#000",
    //   borderRadius: 10,
    //   top: 5,
    //   marginTop: 10
    // },
    mainContainer: {
      width: scale(screenWidth - 110, screenWidth),
      height: "100%",
      backgroundColor: "#fff",
      borderWidth: 1,
      borderColor: "#dddddd",
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3,
      marginLeft: scale(5, screenWidth),
      borderRadius: Math.round(scale(6, screenWidth)),
      flex: 1,
      flexDirection: "row",
      marginTop: vScale((screenHeight / 100) * -0.5, screenHeight),
    },
    match: {
      width: "100%",
      height: "100%",
    },
    item: {
      width: "100%",
      height: "100%",
      gap: vScale(5, screenHeight),
      overflow: "hidden",
    },
    matchDate: {
      width: "100%",
      height: vScale(screenHeight / 30, screenHeight),
      marginTop: vScale(1, screenHeight),
      flexDirection: "row",
      justifyContent: "space-between",
      paddingInline: scale(5, screenWidth),
      alignItems: "center",
      backgroundColor: "#f5f5f5",
      borderBottomEndRadius: Math.round(scale(6, screenWidth)),
      borderBottomStartRadius: Math.round(scale(6, screenWidth)),
    },
    matchTime: {
      width: "80%",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: scale(9, screenWidth),
      marginTop: vScale(2.5, screenHeight),
      marginLeft: scale(25, screenWidth),
      height: vScale(screenHeight / 35, screenHeight),
      backgroundColor: "#f5f5f5",
      borderTopEndRadius: Math.round(scale(15, screenWidth)),
      borderTopStartRadius: Math.round(scale(15, screenWidth)),
    },
    teams: {
      width: "100%",
      flexDirection: "row",
      justifyContent: "space-evenly",
      alignItems: "center",
      paddingInline: scale(8, screenWidth),
      marginTop: vScale(-2.5, screenHeight),
    },
    team: {
      flexDirection: "column",
      alignItems: "center",
      gap: vScale(3, screenHeight),
    },
    logo: {
      width: scale(screenWidth / 10, screenWidth),
      height: vScale(screenHeight / 20, screenHeight),
      borderRadius: Math.round(scale(100, screenWidth)),
      shadowOpacity: 0.05,
      elevation: 3,
      backgroundColor: "#fff",
    },
    teamName: {
      fontFamily: "poppins",
      color: "#1b1a1f",
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      textAlign: "center",
      marginTop: vScale(3, screenHeight),
    },
    leagueName: {
      borderRadius: Math.round(scale(5, screenWidth)),
      flexDirection: "row",
      paddingInline: scale(5, screenWidth),
      alignItems: "center",
      gap: scale(3, screenWidth),
    },
    vsText: {
      color: "#000",
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      marginTop: vScale(20, screenHeight),
      fontWeight: "bold",
      fontFamily: "serif",
    },
    locationText: {
      color: "#9b9b9bff",
      fontStyle: "italic",
      fontSize: normalizeFont(12, screenWidth, screenHeight),
    },
    leagueText: {
      color: "#000",
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      fontWeight: "500",
    },
    timeText: {
      color: "#000",
      fontWeight: "500",
      fontSize: normalizeFont(13, screenWidth, screenHeight),
    },
    hotmatchContainer: {
      position: "absolute",
      top: vScale(10, screenHeight),
      left: scale(120, screenWidth),
      backgroundColor: "#4c008254",
      borderRadius: Math.round(scale(100, screenWidth)),
      padding: scale(5, screenWidth),
      zIndex: 1,
    },
    textcontainer: {
      width: "100%",
      height: vScale(30, screenHeight),
      position: "absolute",
      flex: 1,
      flexDirection: "row",
    },
    league: {
      position: "absolute",
      fontSize: normalizeFont(20, screenWidth, screenHeight),
      fontWeight: "600",
      color: "#fff",
    },
    text: {
      color: "#fff",
      fontSize: normalizeFont(20, screenWidth, screenHeight),
      fontWeight: "bold",
      fontFamily: "serif",
      position: "absolute",
      top: vScale(10, screenHeight),
      left: "55%",
      transform: [{ translateX: -50 }],
      objectFit: "cover",
    },
    generaltext: {
      color: "#4B0082",
      fontSize: normalizeFont(
        (screenWidth / 40) * 2.2,
        screenWidth,
        screenHeight,
      ),
      fontFamily: "serif",
      fontWeight: "bold",
      position: "absolute",
      marginLeft: -scale(screenWidth / 1.6, screenWidth),
      marginTop: vScale((screenHeight / 100) * -7.5, screenHeight),
    },
    adsbannerChallenge: {
      position: "absolute",
      marginTop: vScale(screenHeight / 13, screenHeight),
      marginLeft: scale(screenWidth / 1.5, screenWidth),
      backgroundColor: "#dcdcdc",
      width: scale(screenWidth / 4, screenWidth),
      height: vScale(screenHeight / 15, screenHeight),
      borderRadius: Math.round(scale(6, screenWidth)),
    },
    matchlogo: {
      width: scale(45, screenWidth),
      maxHeight: vScale(45, screenHeight),
      position: "absolute",
      top: vScale(50, screenHeight),
      left: scale(27, screenWidth),
      borderRadius: Math.round(scale(45, screenWidth)),
      overflow: "hidden",
      justifyContent: "center",
      alignItems: "center",
    },
    teamlogo: {
      width: scale(80, screenWidth),
      height: vScale(80, screenHeight),
      objectFit: "contain",
      borderRadius: Math.round(scale(80, screenWidth)),
    },
    sepration: {
      width: "100%",
      height: vScale(screenHeight / 120, screenHeight),
      position: "absolute",
      backgroundColor: "#cccccc",
      marginTop: vScale(screenHeight / 3.3, screenHeight),
    },
    tagContainer: {
      width: scale(screenWidth / 1.1, screenWidth),
      height: "auto",
      right: scale(screenWidth / 50, screenWidth),
      padding: scale(5, screenWidth),
    },
    editPost: {
      flex: 1,
      paddingLeft: scale(10, screenWidth),
    },
    optionsDropdown: {
      width: scale(screenWidth / 2.5, screenWidth),
      alignSelf: "flex-end",
      marginTop: vScale(screenHeight / 20, screenHeight),
      position: screenWidth > 400 ? "relative" : "absolute",
      marginRight: scale(-3.5, screenWidth),
      backgroundColor: "#fff",
      borderRadius: Math.round(scale(8, screenWidth)),
      elevation: 4,
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowRadius: 4,
      padding: scale(8, screenWidth),
      zIndex: 1,
      gap: vScale(10, screenHeight),
    },
    optionDropdown: {
      width: scale(screenWidth / 2.2, screenWidth),
      alignSelf: "flex-end",
      marginTop: vScale(screenHeight / 20, screenHeight),
      position: screenWidth > 400 ? "relative" : "absolute",
      marginRight: scale(-3.5, screenWidth),
      backgroundColor: "#fff",
      borderRadius: Math.round(scale(8, screenWidth)),
      elevation: 4,
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowRadius: 4,
      padding: scale(8, screenWidth),
      zIndex: 1,
      gap: vScale(10, screenHeight),
    },
    arrowUp: {
      left: scale(50, screenWidth),
      width: scale(40, screenWidth),
      height: vScale(7, screenHeight),
      borderRadius: Math.round(scale(20, screenWidth)),
      backgroundColor: "#00000017",
    },
    post: {
      paddingVertical: vScale(8, screenHeight),
      flexDirection: "row",
      alignItems: "center",
      gap: vScale(7, screenHeight),
    },
    backPost: {
      paddingVertical: vScale(8, screenHeight),
      flexDirection: "row",
      alignItems: "center",
      gap: vScale(7, screenHeight),
      justifyContent: "center",
      borderRadius: Math.round(scale(5, screenWidth)),
      backgroundColor: "#eeeeee85",
    },
    select: {
      right: scale(1, screenWidth),
      width: scale(10, screenWidth),
      height: scale(10, screenWidth),
      borderRadius: Math.round(scale(2, screenWidth)),
      backgroundColor: "#000",
      transform: [{ rotate: "45deg" }],
    },
    text3: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      fontWeight: "bold",
      color: "#0b0fe0ff",
    },
    text4: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      fontWeight: "bold",
    },
    text5: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      fontWeight: "bold",
      color: "#ff0000",
    },
    text6: {
      fontSize: normalizeFont(14, screenWidth, screenHeight),
      fontWeight: "bold",
    },
    captionContainer: {
      flex: 1,
      marginRight: scale(10, screenWidth),
      width: scale(300, screenWidth),
    },
    tag: {
      color: "#4B0082",
      fontWeight: "500",
    },
    mention: {
      color: "#4B0082",
      fontWeight: "500",
    },
    seprationLine: {
      width: scale(screenWidth - 20, screenWidth),
      height: vScale(screenHeight / 150, screenHeight),
      bottom: vScale(15, screenHeight),
      right: scale(screenWidth / 50, screenWidth),
      backgroundColor: "#eeeeeeff",
    },
    commentSection: {
      width: scale(screenWidth - 20, screenWidth),
      height: vScale(screenHeight / 13, screenHeight),
      right: scale(11, screenWidth),
      bottom: vScale(10, screenHeight),
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    userInfo: {
      flexDirection: "row",
      alignItems: "center",
      top: vScale(10, screenHeight),
      height: "auto",
      flex: 1,
    },
    userInfoText: {
      flex: 1,
    },
    caption: {
      fontSize: normalizeFont(18, screenWidth, screenHeight),
      fontFamily: "poppins",
      width: scale(screenWidth / 1.1, screenWidth),
      flexWrap: "wrap",
      flexShrink: 1,
    },
    commentIcons: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      width: "40%",
      left: scale(13, screenWidth),
    },
    likesSection: {
      justifyContent: "center",
    },
    likesCounts: {
      height: vScale(screenHeight / 20, screenHeight),
      backgroundColor: "#eeeeeeff",
      borderRadius: Math.round(scale(30, screenWidth)),
      width: scale(screenWidth / 4, screenWidth),
      fontFamily: "sans-serif",
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: scale(5, screenWidth),
    },
    notification: {
      marginLeft: scale(screenWidth / 35, screenWidth),
      backgroundColor: "rgba(76, 0, 130, 0.12)",
      borderRadius: Math.round(scale(50, screenWidth)),
      padding: scale(8, screenWidth),
    },
    searchBar: {
      flex: 1,
      height: "100%",
    },
    textInput: {
      width: "60%",
      height: "100%",
      backgroundColor: "#eeeeee85",
      borderRadius: Math.round(scale(30, screenWidth)),
      paddingLeft: scale(15, screenWidth),
      minHeight: vScale(10, screenHeight),
      maxHeight: vScale(50, screenHeight),
      fontSize: normalizeFont(16, screenWidth, screenHeight), // reduced from 18 -> 16
      left: scale(40, screenWidth),
    },

    text1: {
      fontWeight: "bold",
      fontSize: normalizeFont(16, screenWidth, screenHeight), // reduced from 18 -> 16
      left: scale(10, screenWidth),
    },
    text2: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
    },
    userContainer: {
      width: "100%",
      height: vScale(70, screenHeight),
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderBottomColor: "#cccccc",
      borderBottomWidth: 1,
    },
    containerHobbies: {
      width: "50%",
      height: "100%",
      top: "39%",
      alignItems: "center",
    },
    containerClick: {
      width: "35%",
      height: "100%",
      flexDirection: "row",
      alignItems: "center",
    },
    image: {
      width: scale(60, screenWidth),
      height: vScale(60, screenHeight),
      borderRadius: Math.round(scale(100, screenWidth)),
    },
    cancel: {
      position: "relative",
      right: scale(55, screenWidth),
    },
    searchTextInput: {
      width: "90%",
      height: "100%",
      backgroundColor: "#eeeeee85",
      borderRadius: Math.round(scale(20, screenWidth)),
      paddingLeft: scale(15, screenWidth),
      minHeight: vScale(10, screenHeight),
      maxHeight: vScale(50, screenHeight),
      fontSize: normalizeFont(16, screenWidth, screenHeight), // reduced from 18 -> 16
    },
    share: {
      right: scale(16, screenWidth),
      bottom: vScale(4, screenHeight),
    },
    captionContainer1: {
      flex: 1,
      padding: scale(5, screenWidth),
      alignItems: "center",
      backgroundColor: "#fff",
      gap: vScale(10, screenHeight),
    },
    header1: {
      backgroundColor: "#fff",
      borderRadius: Math.round(scale(5, screenWidth)),
      justifyContent: "space-between",
      alignItems: "center",
      padding: scale(10, screenWidth),
      bottom: vScale(3, screenHeight),
      width: "99%",
      height: vScale(70, screenHeight),
      flexDirection: "row",
      shadowColor: "#000",
      shadowOpacity: 2,
      elevation: 5,
    },
    usercaptionContainer: {
      alignItems: "center",
    },
    profile: {
      width: scale(40, screenWidth),
      height: vScale(40, screenHeight),
      borderRadius: Math.round(scale(20, screenWidth)),
    },
    input: {
      width: "99%",
      minHeight: vScale(45, screenHeight),
      maxHeight: "auto",
      borderColor: "#4B0082",
      borderWidth: 1,
      borderRadius: Math.round(scale(5, screenWidth)),
    },
    updatePostButtonContainer: {
      width: "100%",
      backgroundColor: "#4B0082",
      alignItems: "center",
      height: vScale(40, screenHeight),
      borderRadius: Math.round(scale(5, screenWidth)),
      justifyContent: "center",
    },
    updatePostButton: {
      width: "99%",
      height: vScale(40, screenHeight),
      borderRadius: Math.round(scale(5, screenWidth)),
      justifyContent: "center",
      alignItems: "center",
    },
    saveText: {
      color: "#fff",
      fontSize: normalizeFont(16, screenWidth, screenHeight), // reduced from 18 -> 16
      fontWeight: "bold",
    },
    matchContainer: {
      width: "100%",
      height: "auto",
      padding: scale(10, screenWidth),
      gap: vScale(10, screenHeight),
    },
    textinput: {
      width: "99%",
      minHeight: vScale(40, screenHeight),
      maxHeight: "auto",
      borderColor: "#4B0082",
      borderWidth: 1,
      borderRadius: Math.round(scale(5, screenWidth)),
      paddingLeft: scale(10, screenWidth),
      fontSize: normalizeFont(16, screenWidth, screenHeight),
    },
    animationPress: {
      width: scale(screenWidth / 7, screenWidth),
      height: vScale(screenHeight / 13, screenHeight),
      backgroundColor: "#4c008250",
      borderRadius: Math.round(scale(screenWidth / 5, screenWidth)),
      padding: scale(10, screenWidth),
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOpacity: 0.1,
      elevation: 6,
    },
    animated: {
      width: scale(screenWidth / 6, screenWidth),
      height: vScale(screenHeight / 12, screenHeight),
      overflow: "hidden",
      right: 16,
      zIndex: 9999,
      position: "absolute",
    },
  });
export default indexScreenStyles;
