import { StyleSheet } from "react-native";
import { normalizeFont, scale, vScale } from "./responsive";

const menuStyles = (screenWidth: number, screenHeight: number) =>
  StyleSheet.create({
    container: {
      padding: vScale(5, screenHeight),
      alignItems: "center",
      backgroundColor: "#fff",
    },
    innerContainer: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "space-evenly",
      width: "100%",
    },
    userContainer: {
      minHeight: vScale(100, screenHeight),
      width: "98%",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: "#fff",
      borderRadius: Math.round(scale(5, screenWidth)),
      shadowColor: "#000",
      shadowOpacity: 0.05,
      elevation: 3,
    },
    item: {
      width: "100%",
      height: 110,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      gap: scale(15, screenWidth),
    },
    onpress: {
      height: vScale(90, screenHeight),
      width: "45%",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#fff",
      borderRadius: Math.round(scale(8, screenWidth)),
      shadowColor: "#000",
      shadowOpacity: 0.05,
      elevation: 2,
      overflow: "hidden",
    },
    itemContainer: {
      height: vScale(80, screenHeight),
      width: "90%",
      alignSelf: "center",
      justifyContent: "center",
      alignItems: "center",
      gap: scale(5, screenWidth),
    },
    itemslists: {
      width: "98%",
      height: "40%",
      alignItems: "center",
      justifyContent: "center",
    },
    menuTitle: {
      fontSize: normalizeFont(20, screenWidth, screenHeight),
      fontWeight: "bold",
      color: "black",
      marginRight: scale(50, screenWidth),
    },
    userprofile: {
      width: "50%",
      flexDirection: "row-reverse",
      justifyContent: "flex-start",
      marginRight: scale(20, screenWidth),
    },
    userInfo: {
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "flex-start",
      marginTop: scale(5, screenHeight),
    },
    profilePictureContainer: {
      width: scale(screenWidth / 6, screenWidth),
      height: scale(screenWidth / 6, screenWidth),
      borderRadius: scale(screenWidth / 11, screenWidth),
      position: "absolute",
      overflow: "hidden",
      justifyContent: "center",
      alignItems: "center",
      marginTop: vScale(-15, screenHeight),
      marginLeft: scale(screenWidth / 60, screenWidth),
      shadowColor: "#000",
      shadowOpacity: 0.05,
      elevation: 3.5,
    },
    profilePicture: {
      width: scale(screenWidth / 6, screenWidth),
      height: scale(screenWidth / 6, screenWidth),
    },
    username: {
      fontSize: normalizeFont(18, screenWidth, screenHeight),
      fontWeight: "bold",
      fontFamily: "serif",
      marginTop: vScale(45, screenHeight),
    },
    itemslist: {
      alignSelf: "center",
    },
    text: {
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      width: "100%",
      textAlign: "center",
      color: "#000",
    },
    logout: {
      height: vScale(48, screenHeight),
      width: "98%",
      backgroundColor: "#4B0082",
      borderRadius: Math.round(scale(5, screenWidth)),
      flexDirection: "row",
      gap: 5,
      justifyContent: "center",
      alignItems: "center",
      marginLeft: scale(screenWidth / 80, screenWidth),
    },
    logoutContent: {
      maxWidth: "50%",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: scale(8, screenWidth),
    },
    logoutText: {
      color: "#f9f9f9",
      fontSize: normalizeFont(16, screenWidth, screenHeight),
      fontWeight: "500",
    },
    mainItemContainer: {
      height: vScale(400, screenHeight),
      width: "100%",
      overflow: "hidden",
    },
    mainUserContainer: {
      width: "100%",
      position: "absolute",
      height: 400,
      top: 200,
    },
    editProfile: {
      backgroundColor: "#fff",
      gap: 6,
      borderRadius: 5,
      width: 120,
      height: 35,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
    },
    icon: {
      width: 5,
      height: 35,
      borderRadius: 8,
      justifyContent: "center",
      backgroundColor: "#e8e8e8",
      paddingLeft: 5,
    },
    iconBack: {
      width: screenWidth * 0.11,
      height: screenHeight * 0.05,
      borderWidth: 0.5,
      justifyContent: "center",
      alignItems: "center",
      borderColor: "#4c00829f",
      borderRadius: screenHeight * 0.01,
    },
    iconView: {
      width: "auto",
      height: "auto",
      flexDirection: "row",
      gap: 10,
      justifyContent: "center",
      paddingLeft: 5,
      borderRadius: 8,
      backgroundColor: "#f9f9f9",
    },
    updateProfile: {
      flex: 1,
      gap: 10,
      left: 20,
      width: "100%",
    },
    updatedProfileView: {
      width: "90%",
      height: "auto",
      gap: 2,
    },
    UpdateUserProfileText: {
      fontSize: 17,
      left: 2,
    },
    TextInput: {
      borderWidth: 1,
      borderColor: "#4B0082",
      borderRadius: 5,
      backgroundColor: "#f9f9f9",
      padding: 10,
      marginBottom: 0,
      minHeight: 45,
      maxHeight: 100,
    },
    dropDown: {
      borderWidth: 1,
      borderColor: "#4B0082",
      borderRadius: 5,
      width: "100%",
      backgroundColor: "#f9f9f9",
      height: 45,
    },
    note: {
      marginVertical: 5,
      padding: 10,
      top: 50,
      flexDirection: "row",
      justifyContent: "center",
      backgroundColor: "#bbbbbbff",
      width: "90%",
    },
    updateProfileButton: {
      backgroundColor: "#4B0082",
      borderRadius: 5,
      width: "90%",
      height: 45,
      top: 30,
      alignItems: "center",
      justifyContent: "center",
      marginVertical: 10,
    },
    updateProfileButtonText: {
      color: "#fff",
      fontSize: 18,
    },
    bio: {
      width: "100%",
      minHeight: 30,
      bottom: 20,
    },
    textBio: {
      fontSize: 16,
      color: "#333",
      padding: 10,
    },
    userDetailContainer: {
      width: "95%",
      flex: 1,
      top: 10,
      left: 10,
    },
    postItems: {
      flex: 1,
      aspectRatio: 1,
      margin: 3,
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#4B0082",
      borderRadius: 5,
      overflow: "hidden",
    },
    image: {
      width: "100%",
      height: "100%",
    },
  });

export default menuStyles;
