import { Dimensions, StyleSheet } from "react-native";
const { width: screenWidth, height: screenHeight } = Dimensions.get("window");

const styles = StyleSheet.create({
    container: {
       flex: 1,
       padding: screenHeight * 0.02,
       backgroundColor: '#fff',
       gap: screenWidth  * 0.02,
       alignItems: 'center',
    },
    topBar: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        justifyContent: 'space-between',
        marginBottom: screenHeight * 0.02,
        paddingHorizontal: screenWidth * 0.02,
    },
    title: {
        fontSize: screenHeight * 0.020,
        fontFamily: 'Montserrat-Bold',
        color: '#4B0082',
        fontWeight: 'bold',
        fontStyle: 'italic',
    },
    teamNameInput: {
        width: '90%',
        borderWidth: 1,
        borderColor: '#4B0082',
        borderRadius: 5,
        padding: screenHeight * 0.015,
        fontSize: screenHeight * 0.016,
    },
    handle1: {
        width: '3%',
        height: screenHeight * 0.16,
        backgroundColor: '#2a7541ff',
        alignSelf: 'center',
        top: screenHeight * 0.4,
        left: screenWidth * 0.045,
        position: 'absolute'
    },
    handle2: {
        width: '3%',
        height: screenHeight * 0.16,
        backgroundColor: '#2a7541ff',
        alignSelf: 'center',
        top: screenHeight * 0.4,
        right: screenWidth * 0.045,
        position: 'absolute'
    },
    fieldsContainer: {
        width: '100%',
        height: screenHeight * 0.7,
        justifyContent: 'center',
        padding: screenHeight * 0.0125,
        gap: screenWidth * 0.04,
    },
    field: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        height: '99%',
        backgroundColor: '#31d361e5',
        paddingHorizontal: screenHeight * 0.0125,
        justifyContent: 'space-between',
        gap: screenWidth * 0.04,
    },
    fieldCarpet: {
        width: '100%',
        height: '95%'
    },
    goalArea: {
        position: 'absolute',
        bottom: screenHeight * 0,
        width: '50%',
        height: '20%',
        backgroundColor: '#ffffff90',
        borderTopLeftRadius: screenHeight * 0.02,
        borderTopRightRadius: screenHeight * 0.02,
        left: '25%',
    },
    goalBox: {
        position: 'absolute',
        bottom: screenHeight * 0,
        left: '25%',
        width: '50%',
        height: '20%',
        backgroundColor: '#ffffff90',
        borderTopLeftRadius: screenHeight * 0.02,
        borderTopRightRadius: screenHeight * 0.02,
    },
    goalMouth: {
        position: 'absolute',
        bottom: screenHeight * 0,
        left: '10%',
        width: '80%',
        height: '30%',
        backgroundColor: '#2a7541ff',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
    },
    position: {
        position: 'absolute',
        padding: 5,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: '#fff',
    },
    playerLabel: {
        fontFamily: 'Montserrat-Bold',
        color: '#fff',
        fontWeight: 'bold',
    },
    playerInput: {
        backgroundColor: '#ffffff90',
        borderRadius: 3,
        padding: screenHeight * 0.005,
        marginTop: screenHeight * 0.005,
        width: screenWidth * 0.27,
        position: 'absolute',
        top: screenHeight * 0.035,
        textAlign: 'center',
        color: '#000',
        fontSize: screenHeight * 0.015,
    },
    button: {
        backgroundColor: '#4B0082',
        justifyContent: 'center',
        borderRadius: 5,
        alignItems: 'center',
        marginTop: screenHeight * 0.02,
        width: '90%',
        height: screenHeight * 0.055,
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: screenHeight * 0.020,
    },
});
export default styles;