import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
       flex: 1,
       padding: 10,
       backgroundColor: '#fff',
       gap: 10,
       alignItems: 'center',
    },
    topBar: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        justifyContent: 'space-between',
        marginBottom: 20,
        paddingHorizontal: 6,
    },
    title: {
        fontSize: 18,
        fontFamily: 'Montserrat-Bold',
        color: '#4B0082',
        fontWeight: 'bold',
    },
    teamNameInput: {
        width: '90%',
        borderWidth: 1,
        borderColor: '#4B0082',
        borderRadius: 5,
        padding: 10,
        fontSize: 16,
    },
    handle1: {
        width: '3%',
        height: 150,
        backgroundColor: '#2a7541ff',
        alignSelf: 'center',
        top: 300,
        left: 10,
        position: 'absolute'
    },
    handle2: {
        width: '3%',
        height: 150,
        backgroundColor: '#2a7541ff',
        alignSelf: 'center',
        top: 300,
        right: 10,
        position: 'absolute'
    },
    fieldsContainer: {
        width: '100%',
        height: 500,
        justifyContent: 'center',
        padding: 10,
        gap: 10,
    },
    field: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        height: '99%',
        backgroundColor: '#31d361e5',
        paddingHorizontal: 10,
        justifyContent: 'space-between',
        gap: 10,
    },
    fieldCarpet: {
        width: '100%',
        height: '95%'
    },
    goalArea: {
        position: 'absolute',
        bottom: 0,
        width: '50%',
        height: '20%',
        backgroundColor: '#ffffff90',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        left: '25%',
    },
    goalBox: {
        position: 'absolute',
        bottom: 0,
        left: '25%',
        width: '50%',
        height: '20%',
        backgroundColor: '#ffffff90',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
    },
    goalMouth: {
        position: 'absolute',
        bottom: 0,
        left: '10%',
        width: '80%',
        height: '30%',
        backgroundColor: '#2a7541ff',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
    },
    position: {
        position: 'absolute',
        padding: 5,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: '#fff',
    },
    playerLabel: {
        fontFamily: 'Montserrat-Bold',
        color: '#fff',
        fontWeight: 'bold',
    },
    playerInput: {
        backgroundColor: '#ffffff90',
        borderRadius: 3,
        padding: 2,
        marginTop: 5,
        width: 80,
        position: 'absolute',
        top: 25,
        textAlign: 'center',
        color: '#000'
    },
    button: {
        backgroundColor: '#4B0082',
        padding: 15,
        borderRadius: 5,
        alignItems: 'center',
        marginTop: 20,
        width: '90%',
        height: 45,
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
});
export default styles;